### ISSUE TITLE
Integrate AWS-PlantUML into PlantUML

### ISSUE THREAD

**Issue by arnaudroques** [milo-minderbinder/AWS-PlantUML#20]
Many thanks for this set of sprites and goodies. It's really super-useful.

Actually, it's so useful that we would like to include these to the standard distribution of PlantUML.
Following the C convention for "C standard library" (see https://en.wikipedia.org/wiki/C_standard_library ), users would be able to use something like:

```
!include <aws/common.puml>
!include <aws/ApplicationServices/AmazonAPIGateway/AmazonAPIGateway.puml>
!include <aws/Compute/AWSLambda/AWSLambda.puml>
!include <aws/Compute/AWSLambda/LambdaFunction/LambdaFunction.puml>
!include <aws/Database/AmazonDynamoDB/AmazonDynamoDB.puml>
!include <aws/Database/AmazonDynamoDB/table/table.puml>
!include <aws/General/AWScloud/AWScloud.puml>
!include <aws/General/client/client.puml>
!include <aws/SDKs/JavaScript/JavaScript.puml>
!include <aws/General/user/user.puml>
!include <aws/Storage/AmazonS3/AmazonS3.puml>
!include <aws/Storage/AmazonS3/bucket/bucket.puml>
```

This would simply work out-of-the-box, without any other requirement.
The only drawback is that it will increase plantuml.jar size of 2.5 Mo.

1) What do you think about it ?
2) Would you agree that we distribute your "dist" folder into our product ?
3) If you wish, we can also cite you in 
```
@startuml
authors
@enduml
```
4) In our mind, the documentation for AWS-PlantUML would remain in this repository, and this repository will be the "official" version for AWS-PlantUML. We will just copy the "dist" folder. So that you will be able to continue to improve it.

Does it sound good to you ?

**Comment by Ducatel** [comment]
This is a great idea 👍

**Comment by milo-minderbinder** [comment]
Responding on mobile so apologies in advance for any spelling errors. First off - thank _you_ for an indispensable diagramming tool, from someone in AppSec who has no free-form diagramming skills, yet has to update/amend diagrams constantly! I'm super flattered that you, and the other users of AWS-PlantUML, have shown interest in this project, and I'm glad you've found it useful. Even more so that you consider it useful enough to integrate into the core PlantUML project - so thanks!

I'm certainly not averse to the idea, and from its inception this project has been something I've put up on GitHub for anyone to use in whatever way is useful to them. In that spirit, and given that this project would not exist without PlantUML in the first place, if the PlantUML project wants to include AWS-PlantUML's dist with the standard distribution, I'd consider it an honor to contribute to the project in that way (a credit in the `@authors` would be great! 🙂), and leave that decision up to you with my permission.

I'll be brief(ish) here until I can get in front of my computer to provide more color and context, but I do have some additional thoughts regarding the size impact to the jar and how that could be reduced, how to ensure the included dist meets the majority of use cases while still enabling customization and flexibility for alternative use cases/preferences, etc.. I'll also share a more generic implementation I haven't pushed to a public repo yet, which allows users to similarly  create configurable sprites and macros for other icon sets (e.g for other platforms, like Azure or GCP, or for miscellaneous architecural components like Jenkins, nginx, whatever).

**Comment by arnaudroques** [comment]
Ok, so we've build a new beta https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0
With this beta, you can have:
```
@startuml
!include <aws/common.puml>
!include <aws/Storage/AmazonS3/AmazonS3.puml>
!include <aws/Storage/AmazonS3/bucket/bucket.puml>

AMAZONS3(s3_internal)
AMAZONS3(s3_partner,"Vendor's S3")
s3_internal <-- s3_partner
@enduml
```

Few remarks:
* We have also modified the `@startuml/authors/@enduml`. Please tell us if it's ok for you !
* You can open the .jar file with any zip editor. There is a new "stdlib" folder. Include are searched in this folder. You can even patch our beta.
* We have named your library "aws" but maybe a better name is possible
* We've noticed that you have `@startuml` and `@enduml` in every .puml file. Actually this is not really need, so maybe you can remove them in all files
* We are concerned about case: we would like the !include to be case insensitive. Unfortunately, this means that we should rename all your files in lowercase. Let me explain why : if in "stdlib" filepath is completely lowercased (this is the case for the test files foo/example1.puml we've put in the beta), then the following include are working:
 `!include <foo/example1.puml>`
 `!include <Foo/Example1.puml>`
 `!include <FOO/example1.puml>`
* The .puml extension is optional and the following is also working:
```
@startuml
!include <aws/common>
!include <aws/Storage/AmazonS3/AmazonS3>
!include <aws/Storage/AmazonS3/bucket/bucket>

AMAZONS3(s3_internal)
AMAZONS3(s3_partner,"Vendor's S3")
s3_internal <-- s3_partner
@enduml
```
This is a first draft, so we are open to suggestions!
It's really nice that you have gather so many goodies in AWS-PlantUML. I'm sure that other users will love that!

**Comment by milo-minderbinder** [comment]
@arnaudroques no worries - just reverted the pathname changes and related doc changes to `master` and the `release/17-10-18` branches.

**Comment by arnaudroques** [comment]
Great! We've published a new beta with the last version of aws library.

Good question about the process: we've just created a new repository https://github.com/plantuml/plantuml-stdlib that contains only the standard library.

This way, you can create PR to this repository whenever you want.
The changes will be added in upcoming releases and betas.
